name: Auto Create Pull Request

on:
  push:
    branches:
      - 'feature/**'  # Any feature branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: main
          pr_title: 'Auto PR from ${{ github.ref_name }}'
          pr_body: 'This PR was automatically created from feature branch.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
